services:
  db:
    image: postgres:17
    container_name: trabalho-final-gc-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trabalho-final-db
    ports:
      - "5432:5432"
    volumes:
      - trabalho-final-gc-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d trabalho-final-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: trabalho-final-gc-server
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 5000
      DATABASE_URL: postgres://root:root@db:5432/trabalho-final-db
      FRONTEND_URL: http://localhost:3001
      NODE_ENV: development
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: trabalho-final-gc-frontend
    depends_on:
      - server
    environment:
      API_URL: http://localhost:5000/api
      WATCHPACK_POLLING: "true"
    ports:
      - "3001:3000"

volumes:
  trabalho-final-gc-db:
